
# Project Name
name: 'snowflake_dwh'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]


target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  +persist_docs:
    relation: true
    columns: true
  
  # dbt_meta_testing
  +required_docs: true

  # elementary
  elementary:
    +schema: 'dq_elementary'


  snowflake_dwh:
    staging:
      primary_sales:
        +schema: primary_sales
        +materialized: view
      
      secondary_sales:
        +schema: secondary_sales
        +materialized: view
      
      payments:
        +schema: payments
        +materialized: view
    
    ods:
      +transient: false
      sales:
        +schema: ods_sales
        +materialized: table
      
      payments:
        +schema: ods_payments
        +materialized: table
    
    dwh:
      +transient: false
      sales:
        +schema: dwh
        +materialized: table


# Configuring snapshots
snapshots:
  +persist_docs:
    relation: true
    columns: true


# Configuring seeds
seeds:
  +persist_docs:
    relation: true
    columns: true


tests:
  +store_failures: true
  +schema: dq_tests


vars:
